server:
  port: 9900

spring:
  application:
    name: auth-service

  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}

  rabbitmq:
    port: 5672

logging:
  level:
    org.hibernate.SQL: debug

eureka:
  instance:
    instance-id: auth-service

  client:
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
