server:
  port: 8080

spring:
  config:
    activate:
      on-profile: dev

  application:
    name: member-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/modu-chat?serverTimezone=Asia/Seoul
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

  kafka:
    consumer:
      group-id: member-service-group

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

  circuit-breaker:
    enabled: true

resilience4j:
  retry:
    configs:
      default:
        max-attempts: 5
        waitDuration: 500
    instances:
      customRetry:
        base-config: default
  circuit-breaker:
    configs:
      default:
        waitDurationInOpenState: 30s
        slowCallRateThreshold: 80
        slowCallDurationThreshold: 5s
        registerHealthIndicator: true
    instances:
      default:
        baseConfig: default
  time-limiter:
    configs:
      default:
        timeoutDuration: 5s
        cancelRunningFuture: true

logging:
  level:
    org.hibernate.SQL: debug

management:
  server:
    port: 8082
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true

eureka:
  instance:
    instance-id: member-service

  client:
    register-with-eureka: true
    fetch-registry: true
